import { Student } from '../types';

export const INITIAL_SAMPLE_STUDENTS: Omit<Student, 'id'>[] = [
  {
    studentId: 'STU-2026-001',
    grNumber: '4120',
    admissionYear: '2026-2027',
    admissionDate: '2026-06-15',
    admissionClass: '9th',
    studentName: 'Deshmukh Prathamesh Rajesh',
    studentNameLocal: 'देशमुख प्रथमेश राजेश',
    fatherName: 'Rajesh Vasantrao Deshmukh',
    fatherNameLocal: 'राजेश वसंतराव देशमुख',
    motherName: 'Sunita Rajesh Deshmukh',
    motherNameLocal: 'सुनिता राजेश देशमुख',
    birthDate: '2011-04-12',
    birthPlace: 'Pune, Maharashtra',
    birthPlaceLocal: 'पुणे, महाराष्ट्र',
    nationality: 'Indian',
    motherTongue: 'Marathi',
    religion: 'Hindu',
    religionLocal: 'हिंदू',
    caste: 'Maratha',
    casteLocal: 'मराठा',
    subCaste: '96 Kuli',
    subCasteLocal: '९६ कुळी',
    uid: '4589 1234 5678',
    previousSchool: 'Adarsh High School, Kothrud, Pune (Class 8th Passed)',
    previousSchoolLocal: 'आदर्श हायस्कूल, कोथरूड, पुणे (इयत्ता ८ वी उत्तीर्ण)',
    mobile: '98221 45678',
    address: 'Flat No. 302, Sai Shraddha Residency, Paud Road, Pune - 411038',
    academicProgress: 'Excellent (A+ Grade)',
    academicProgressLocal: 'उत्कृष्ट (अ+ श्रेणी)',
    behaviour: 'Very Good & Cooperative',
    behaviourLocal: 'उत्कृष्ट व सहकार्यशील',
    leavingReason: '',
    leavingReasonLocal: '',
    certificateDate: '',
    headmasterSignature: 'Approved by Headmaster',
    createdAt: '2026-06-15T09:30:00Z',
    updatedAt: '2026-06-15T09:30:00Z'
  },
  {
    studentId: 'STU-2026-002',
    grNumber: '4121',
    admissionYear: '2026-2027',
    admissionDate: '2026-06-16',
    admissionClass: '10th',
    studentName: 'Patil Ananya Sunil',
    studentNameLocal: 'पाटील अनन्या सुनील',
    fatherName: 'Sunil Mahadev Patil',
    fatherNameLocal: 'सुनील महादेव पाटील',
    motherName: 'Archana Sunil Patil',
    motherNameLocal: 'अर्चना सुनील पाटील',
    birthDate: '2010-09-24',
    birthPlace: 'Kolhapur, Maharashtra',
    birthPlaceLocal: 'कोल्हापूर, महाराष्ट्र',
    nationality: 'Indian',
    motherTongue: 'Marathi',
    religion: 'Hindu',
    religionLocal: 'हिंदू',
    caste: 'Maratha',
    casteLocal: 'मराठा',
    subCaste: 'Maratha',
    subCasteLocal: 'मराठा',
    uid: '7845 9632 1012',
    previousSchool: 'Chatrapati Shahu Vidyalaya, Kolhapur (Class 9th Passed)',
    previousSchoolLocal: 'छत्रपती शाहू विद्यालय, कोल्हापूर (इयत्ता ९ वी उत्तीर्ण)',
    mobile: '94220 78912',
    address: 'Plot 45, Vidyanagar, Baner Road, Pune - 411045',
    academicProgress: 'Good (First Class)',
    academicProgressLocal: 'उत्तम (प्रथम श्रेणी)',
    behaviour: 'Good & Disciplined',
    behaviourLocal: 'उत्तम व शिस्तबद्ध',
    leavingReason: '',
    leavingReasonLocal: '',
    certificateDate: '',
    headmasterSignature: 'Approved by Headmaster',
    createdAt: '2026-06-16T10:00:00Z',
    updatedAt: '2026-06-16T10:00:00Z'
  },
  {
    studentId: 'STU-2026-003',
    grNumber: '4122',
    admissionYear: '2026-2027',
    admissionDate: '2026-06-18',
    admissionClass: '8th',
    studentName: 'Joshi Aditya Prasad',
    studentNameLocal: 'जोशी आदित्य प्रसाद',
    fatherName: 'Prasad Narayan Joshi',
    fatherNameLocal: 'प्रसाद नारायण जोशी',
    motherName: 'Medha Prasad Joshi',
    motherNameLocal: 'मेधा प्रसाद जोशी',
    birthDate: '2012-11-05',
    birthPlace: 'Nashik, Maharashtra',
    birthPlaceLocal: 'नाशिक, महाराष्ट्र',
    nationality: 'Indian',
    motherTongue: 'Marathi',
    religion: 'Hindu',
    religionLocal: 'हिंदू',
    caste: 'Brahmin',
    casteLocal: 'ब्राह्मण',
    subCaste: 'Deshastha',
    subCasteLocal: 'देशस्थ',
    uid: '9658 7412 3652',
    previousSchool: 'Saraswati Bal Mandir, Nashik (Class 7th Passed)',
    previousSchoolLocal: 'सरस्वती बाल मंदिर, नाशिक (इयत्ता ७ वी उत्तीर्ण)',
    mobile: '98901 23456',
    address: 'B-14, Shanti Niketan, Karve Nagar, Pune - 411052',
    academicProgress: 'Outstanding',
    academicProgressLocal: 'अतिउत्कृष्ट',
    behaviour: 'Exemplary',
    behaviourLocal: 'अनुकरणीय',
    leavingReason: '',
    leavingReasonLocal: '',
    certificateDate: '',
    headmasterSignature: 'Approved by Headmaster',
    createdAt: '2026-06-18T11:15:00Z',
    updatedAt: '2026-06-18T11:15:00Z'
  },
  {
    studentId: 'STU-2025-014',
    grNumber: '3980',
    admissionYear: '2025-2026',
    admissionDate: '2025-06-12',
    admissionClass: '9th',
    studentName: 'Shinde Rohan Prakash',
    studentNameLocal: 'शिंदे रोहन प्रकाश',
    fatherName: 'Prakash Baburao Shinde',
    fatherNameLocal: 'प्रकाश बाबुराव शिंदे',
    motherName: 'Surekha Prakash Shinde',
    motherNameLocal: 'सुरेखा प्रकाश शिंदे',
    birthDate: '2011-02-18',
    birthPlace: 'Satara, Maharashtra',
    birthPlaceLocal: 'सातारा, महाराष्ट्र',
    nationality: 'Indian',
    motherTongue: 'Marathi',
    religion: 'Hindu',
    religionLocal: 'हिंदू',
    caste: 'SC',
    casteLocal: 'अनुसूचित जाती (SC)',
    subCaste: 'Mahar',
    subCasteLocal: 'महार',
    uid: '3214 5698 7412',
    previousSchool: 'Zilla Parishad Primary School, Satara',
    previousSchoolLocal: 'जिल्हा परिषद प्राथमिक शाळा, सातारा',
    mobile: '97664 12389',
    address: 'Guruwar Peth, Near Shitala Devi Mandir, Pune - 411002',
    academicProgress: 'Satisfactory',
    academicProgressLocal: 'समाधानकारक',
    behaviour: 'Good',
    behaviourLocal: 'उत्तम',
    leavingReason: '',
    leavingReasonLocal: '',
    certificateDate: '',
    headmasterSignature: 'Approved by Headmaster',
    createdAt: '2025-06-12T08:45:00Z',
    updatedAt: '2025-06-12T08:45:00Z'
  },
  {
    studentId: 'STU-2025-025',
    grNumber: '3995',
    admissionYear: '2025-2026',
    admissionDate: '2025-06-20',
    admissionClass: '10th',
    studentName: 'Khan Ayesha Mohammed',
    studentNameLocal: 'खान आयशा मोहम्मद',
    fatherName: 'Mohammed Arif Khan',
    fatherNameLocal: 'मोहम्मद आरिफ खान',
    motherName: 'Farzana Mohammed Khan',
    motherNameLocal: 'फरझाना मोहम्मद खान',
    birthDate: '2010-07-30',
    birthPlace: 'Aurangabad, Maharashtra',
    birthPlaceLocal: 'छत्रपती संभाजीनगर (औरंगाबाद), महाराष्ट्र',
    nationality: 'Indian',
    motherTongue: 'Urdu',
    religion: 'Muslim',
    religionLocal: 'मुस्लिम',
    caste: 'OBC',
    casteLocal: 'इतर मागास वर्ग (OBC)',
    subCaste: 'Pinjari',
    subCasteLocal: 'पिंजारी',
    uid: '8520 1479 6325',
    previousSchool: 'National English Medium School, Pune',
    previousSchoolLocal: 'नॅशनल इंग्लिश मीडियम स्कूल, पुणे',
    mobile: '93710 44556',
    address: 'H.No 88, Camp Area, MG Road, Pune - 411001',
    academicProgress: 'Very Good (Distinction in Science)',
    academicProgressLocal: 'अतिउत्तम (विज्ञान विषयात विशेष प्राविण्य)',
    behaviour: 'Well Behaved',
    behaviourLocal: 'सद्वर्तनी व आज्ञाधारक',
    leavingReason: 'Parent Transfer to Mumbai',
    leavingReasonLocal: 'पालकांची मुंबई येथे बदली',
    certificateDate: '2026-04-10',
    headmasterSignature: 'Approved by Headmaster',
    createdAt: '2025-06-20T10:30:00Z',
    updatedAt: '2026-04-10T14:20:00Z'
  },
  {
    studentId: 'STU-2024-008',
    grNumber: '3810',
    admissionYear: '2024-2025',
    admissionDate: '2024-06-14',
    admissionClass: '11th',
    studentName: 'Gaikwad Tanvi Santosh',
    studentNameLocal: 'गायकवाड तन्वी संतोष',
    fatherName: 'Santosh Vitthal Gaikwad',
    fatherNameLocal: 'संतोष विठ्ठल गायकवाड',
    motherName: 'Kavita Santosh Gaikwad',
    motherNameLocal: 'कविता संतोष गायकवाड',
    birthDate: '2009-05-14',
    birthPlace: 'Solapur, Maharashtra',
    birthPlaceLocal: 'सोलापूर, महाराष्ट्र',
    nationality: 'Indian',
    motherTongue: 'Marathi',
    religion: 'Hindu',
    religionLocal: 'हिंदू',
    caste: 'OBC',
    casteLocal: 'इतर मागास वर्ग (OBC)',
    subCaste: 'Mali',
    subCasteLocal: 'माळी',
    uid: '1478 5236 9654',
    previousSchool: 'New English School, Solapur (Class 10th Passed with 91%)',
    previousSchoolLocal: 'न्यू इंग्लिश स्कूल, सोलापूर (इयत्ता १० वी ९१% गुणांसह उत्तीर्ण)',
    mobile: '98233 66778',
    address: 'Flat 104, Green Palms, Hadapsar, Pune - 411028',
    academicProgress: 'Excellent',
    academicProgressLocal: 'उत्कृष्ट',
    behaviour: 'Punctual and Dedicated',
    behaviourLocal: 'वेळेचे पालन करणारा व निष्ठावान',
    leavingReason: '',
    leavingReasonLocal: '',
    certificateDate: '',
    headmasterSignature: 'Approved by Headmaster',
    createdAt: '2024-06-14T09:00:00Z',
    updatedAt: '2024-06-14T09:00:00Z'
  }
];
